name: CI

on:
  push:
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          rm .dockerignore
          mv .env.test .env
          docker build -t app-test --target symfony_php .
          docker run --entrypoint sh app-test -c "php bin/console doctrine:database:create && php bin/console doctrine:migrations:migrate"
          docker run --entrypoint sh app-test -c "php bin/phpunit"
  publish-docker:
    needs: [ docker-test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env.test to .env
        run: cp .env.test .env
      - name: Build PHP image
        run: docker build -t attilamolnar93/sharex-custom-uploader:latest-fpm --target symfony_php .
      - name: Build caddy image
        run: docker build -t attilamolnar93/sharex-custom-uploader:latest-caddy --target symfony_caddy .
      - name: Log into Docker Hub Container Registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u attilamolnar93 --password-stdin
      - name: Push PHP image to Docker Hub Container Registry
        run: docker push attilamolnar93/sharex-custom-uploader:latest-fpm
      - name: Push caddy image to Docker Hub Container Registry
        run: docker push attilamolnar93/sharex-custom-uploader:latest-caddy
